docs: document the Host Rules UI for Mend-hosted Apps
justo-mend/renovate pull request #5
Opened 2024-11-08 11:01 UTC by justo-mend

## Changes

Added docs for Host Rules UI in the Developer Portal

## Context

New UI has been added in the Developer Portal for creating Host Rules.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-08 11:09 UTC, rarkins requested changes
This is not a good example to use like this, because:
1. If any github user applies this example, it can break break the(ir) app by overriding the app token
2. It should have a match host for github.com

If you want to show a github host rule for those on bitbucket/azdo who need it for fetching, then add more description making that part clear.

2024-11-12 08:30 UTC, rarkins requested changes

2024-11-12 08:30 UTC, rarkins commented on docs/usage/mend-hosted/.pages
> +  - 'Secrets and Host Rules': 'app-secrets.md'
```suggestion
  - 'Credentials': 'credentials.md'
```

Rename the file. Is it linked from anywhere external?

2024-11-12 08:30 UTC, rarkins commented on docs/usage/mend-hosted/app-secrets.md
> +4. Use can reference the secret from Renovate config files inside the repo.
```suggestion
4. Reference the secret from Renovate config files inside the repo.
```

2024-11-12 08:30 UTC, rarkins commented on docs/usage/mend-hosted/app-secrets.md
> +### Adding a host rule
```suggestion
### Adding a host rule through the UI

You can centrally add/configure Host Rules through the Mend UI as an alternative to including them in Renovate presets.
```

2024-11-12 08:30 UTC, rarkins commented on docs/usage/mend-hosted/app-secrets.md
> +   As an example, if you are a Bitbucket or Azure DevOps user, and you want to specify the GITHUB_TOKEN to fetch release notes, you could create a host rule like this:
```suggestion
   As an example, if you are a Bitbucket or Azure DevOps user, and you want to specify a github.com token to fetch release notes and enable github-based datasources, you could create a host rule like this:
```

2024-11-12 08:34 UTC, justo-mend commented on docs/usage/mend-hosted/.pages
> +  - 'Secrets and Host Rules': 'app-secrets.md'
I'll check for external references.

2024-11-14 12:16 UTC, rarkins commented
This is ready to raise to the main repo, if tests pass

2024-11-14 15:24 UTC, justo-mend commented
PR created to merge this branch into the main renovatebot repo.
Closing this PR.

2024-11-14 15:24 UTC, closed without merging